export const LIST = "LIST_SCHEDULE";
export const LIST_SUCCESS = "LIST_SCHEDULE_SUCCESS";
export const LIST_FAILED = "LIST_SCHEDULE_FAILED";

export const DETAIL = "DETAIL_SCHEDULE";
export const DETAIL_SUCCESS = "DETAIL_SCHEDULE_SUCCESS";
export const DETAIL_FAILED = "DETAIL_SCHEDULE_FAILED";

export const RESET_DATA = "RESET_DATA_SCHEDULE";
