export const LIST = "LIST_SCHEDULE";
export const LIST_SUCCESS = "LIST_SCHEDULE_SUCCESS";
export const LIST_FAILED = "LIST_SCHEDULE_FAILED";

export const DETAIL = "DETAIL_SCHEDULE";
export const DETAIL_SUCCESS = "DETAIL_SCHEDULE_SUCCESS";
export const DETAIL_FAILED = "DETAIL_SCHEDULE_FAILED";

export const CONFIRM_REMINDERCARE = "CONFIRM_REMINDERCARE";
export const CONFIRM_REMINDERCARE_SUCCESS = "CONFIRM_REMINDERCARE_SUCCESS";
export const CONFIRM_REMINDERCARE_FAILED = "CONFIRM_REMINDERCARE_FAILED";

export const CONFIRM_REMINDERCARE_DETAIL = "CONFIRM_REMINDERCARE_DETAIL";
export const CONFIRM_REMINDERCARE_DETAIL_SUCCESS =
  "CONFIRM_REMINDERCARE_DETAIL_SUCCESS";
export const CONFIRM_REMINDERCARE_DETAIL_FAILED =
  "CONFIRM_REMINDERCARE_DETAIL_FAILED";

export const CONFIRM_SCHEDULES = "CONFIRM_SCHEDULES";
export const CONFIRM_SCHEDULES_SUCCESS = "CONFIRM_SCHEDULES_SUCCESS";
export const CONFIRM_SCHEDULES_FAILED = "CONFIRM_SCHEDULES_FAILED";

export const DESTROY_SCHEDULES = "DESTROY_SCHEDULES";
export const DESTROY_SCHEDULES_SUCCESS = "DESTROY_SCHEDULES_SUCCESS";
export const DESTROY_SCHEDULES_FAILED = "DESTROY_SCHEDULES_FAILED";

export const RESET_DATA = "RESET_DATA_SCHEDULE";
