export const GET = "GET_SETTING";
export const GET_SUCCESS = "GET_SETTING_SUCCESS";
export const GET_FAILED = "GET_SETTING_FAILED";

export const UPDATE = "UPDATE_SETTING";
export const UPDATE_SUCCESS = "UPDATE_SETTING_SUCCESS";
export const UPDATE_FAILED = "UPDATE_SETTING_FAILED";

export const RESET_DATA = "RESET_DATA_SETTING";
