export const LIST = "LIST_BOOKING_DETAIL";
export const LIST_SUCCESS = "LIST_BOOKING_DETAIL_SUCCESS";
export const LIST_FAILED = "LIST_BOOKING_DETAIL_FAILED";

export const CONFIRM_BOOKINGDETAIL = "CONFIRM_BOOKINGDETAIL";
export const CONFIRM_BOOKINGDETAIL_SUCCESS = "CONFIRM_BOOKINGDETAIL_SUCCESS";
export const CONFIRM_BOOKINGDETAIL_FAILED = "CONFIRM_BOOKINGDETAIL_FAILED";

export const DESTROY_BOOKINGDETAIL = "DESTROY_BOOKINGDETAIL";
export const DESTROY_BOOKINGDETAIL_SUCCESS = "DESTROY_BOOKINGDETAIL_SUCCESS";
export const DESTROY_BOOKINGDETAIL_FAILED = "DESTROY_BOOKINGDETAIL_FAILED";

export const RESET_DATA = "RESET_DATA_BOOKING";
