export const LIST = "LIST_PRODUCT";
export const LIST_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_FAILED = "LIST_PRODUCT_FAILED";

export const ADD = "ADD_PRODUCT";
export const ADD_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_FAILED = "ADD_PRODUCT_FAILED";

export const EDIT = "EDIT_PRODUCT";
export const EDIT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_FAILED = "EDIT_PRODUCT_FAILED";

export const UPDATE = "UPDATE_PRODUCT";
export const UPDATE_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE = "DELETE_PRODUCT";
export const DELETE_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_FAILED = "DELETE_PRODUCT_FAILED";

export const DETAIL = "DETAIL_PRODUCT";
export const DETAIL_SUCCESS = "DETAIL_PRODUCT_SUCCESS";
export const DETAIL_FAILED = "DETAIL_PRODUCT_FAILED";

export const RESET_DATA = "RESET_DATA_PRODUCT";
