export const LIST = "LIST_BOOKING";
export const LIST_SUCCESS = "LIST_BOOKING_SUCCESS";
export const LIST_FAILED = "LIST_BOOKING_FAILED";

export const DETAIL = "DETAIL_BOOKING";
export const DETAIL_SUCCESS = "DETAIL_BOOKING_SUCCESS";
export const DETAIL_FAILED = "DETAIL_BOOKING_FAILED";

export const CONFIRM = "CONFIRM_BOOKING";
export const CONFIRM_SUCCESS = "CONFIRM_BOOKING_SUCCESS";
export const CONFIRM_FAILED = "CONFIRM_BOOKING_FAILED";

export const DESTROY = "DESTROY_BOOKING";
export const DESTROY_SUCCESS = "DESTROY_BOOKING_SUCCESS";
export const DESTROY_FAILED = "DESTROY_BOOKING_FAILED";

export const RESET_DATA = "RESET_DATA_BOOKING";
