export const LIST = "LIST_BOOKING";
export const LIST_SUCCESS = "LIST_BOOKING_SUCCESS";
export const LIST_FAILED = "LIST_BOOKING_FAILED";

export const ADD = "ADD_BOOKING";
export const ADD_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_FAILED = "ADD_BOOKING_FAILED";

export const EDIT = "EDIT_BOOKING";
export const EDIT_SUCCESS = "EDIT_BOOKING_SUCCESS";
export const EDIT_FAILED = "EDIT_BOOKING_FAILED";

export const UPDATE = "UPDATE_BOOKING";
export const UPDATE_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_FAILED = "UPDATE_BOOKING_FAILED";

export const DELETE = "DELETE_BOOKING";
export const DELETE_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_FAILED = "DELETE_BOOKING_FAILED";

export const DETAIL = "DETAIL_BOOKING";
export const DETAIL_SUCCESS = "DETAIL_BOOKING_SUCCESS";
export const DETAIL_FAILED = "DETAIL_BOOKING_FAILED";

export const RESET_DATA = "RESET_DATA_BOOKING";
